# Site settings
title: Tian's Profile
email: twu075@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn to use GitHub pages with Wheelhouse.io and Patchwork!
baseurl: "https://github.com/twu075"
url: "http://twu075.github.io"
twitter_username: N/A
github_username:  twu075
permalink: /TW/:2016/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
